### ISSUE TITLE
404 error is returned from Spotify's playlist

### ISSUE THREAD

**Issue by rootsnet** [timrae/spotify_to_tidal#102]
The issue started occurring on November 28, 2024. I am using version 1.0.4. Could you please assist me?

HTTP Error for GET to https://api.spotify.com/v1/playlists/37i9dQZF1DWWvmOXYvR5a6 with Params: {'fields': None, 'market': None, 'additional_types': 'track'} returned 404 due to Resource not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 275, in _internal_call
Opening Spotify session
Opening Tidal session
Error getting Spotify playlist 37i9dQZF1DWWvmOXYvR5a6
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/playlists/37i9dQZF1DWWvmOXYvR5a6?additional_types=track

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/spotify_to_tidal", line 8, in <module>
    sys.exit(main())
  File "/app/spotify_to_tidal/src/spotify_to_tidal/__main__.py", line 34, in main
    _sync.sync_playlists_wrapper(spotify_session, tidal_session, _sync.get_playlists_from_config(spotify_session, tidal_session, config), config)
  File "/app/spotify_to_tidal/src/spotify_to_tidal/sync.py", line 403, in get_playlists_from_config
    raise e
  File "/app/spotify_to_tidal/src/spotify_to_tidal/sync.py", line 400, in get_playlists_from_config
    spotify_playlist = spotify_session.playlist(playlist_id=spotify_id)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 666, in playlist
    return self._get(
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 327, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 297, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/playlists/37i9dQZF1DWWvmOXYvR5a6?additional_types=track:
 Resource not found, reason: None

**Comment by joshrmcdaniel** [comment]
Is this a "Made for you" playlist? It appears spotify blocks access to that API endpoint https://github.com/spotify/web-api/issues/324

**Comment by blakkd** [comment]
@rootsnet if you run into this, create a new playlist and add the tracks from the "for you" playlist to this new "regular" playlist. Then sync it instead ;)
