### ISSUE TITLE
Install borks at:  "python setup.py egg_info did not run successfully."

### ISSUE THREAD

**Issue by myriad007** [timrae/spotify_to_tidal#103]
Unable to get this to install properly on Ubuntu 22.05 getting the following error:
`Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-a_5f4ser/ratelimit.egg-info
      writing /tmp/pip-pip-egg-info-a_5f4ser/ratelimit.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-a_5f4ser/ratelimit.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-a_5f4ser/ratelimit.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-a_5f4ser/ratelimit.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-pip-egg-info-a_5f4ser/ratelimit.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-1usau_h6/ratelimit_ed6c80dc89634660853dc9e882d0f763/setup.py", line 10, in <module>
          setup(
        File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 313, in run
          self.find_sources()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 321, in find_sources
          mm.run()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 549, in run
          self.prune_file_list()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/command/sdist.py", line 162, in prune_file_list
          super().prune_file_list()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/sdist.py", line 380, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_core_metadata.py", line 267, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`
Any suggestions as to how I can fix this?

**Comment by timrae** [comment]
https://github.com/pypa/setuptools/issues/4483

**Comment by timrae** [comment]
In the future, when making use of open source projects, might I suggest that you at least _make an attempt_ at solving issues yourself before asking the project maintainers for help?

This is clearly an issue with your local python environment, which you could have found a solution to in about 10 seconds by googling the error message.

In case you're new to this, here's an [excerpt](https://github.com/AndyObtiva/open-source-etiquette?tab=readme-ov-file#open-source-project-users) I found about open source etiquette:

> * Generally, avoid asking questions about an open-source project before putting in the effort to try it yourself (unless you get stuck of course), as that is considered the lazy behavior of unskilled software engineers and actual trolls, and you might get ignored for it. Respectful software engineers always give open-source projects the benefit of the doubt and do due diligence before asking questions to avoid wasting the project author's time.
> * Do not open an issue when the effort to implement a fix or a feature is very small, including documentation changes. Open a pull request instead. Remember that open-source projects are a community effort. Finding a small issue or feature that is quick to implement is your opportunity to make a contribution!
> * When reporting an issue, provide a step-by-step scenario for reproducing the issue if it is easy to reproduce, and follow troubleshooting instructions that project authors might give you to help you troubleshoot the issue further.
> * Never put pressure on an open-source project's author if he is unavailable or too busy as that comes across as disrespectful and might discourage them from becoming available, especially given that they offer the project as a free service. There is never a need to sweat an author's lack of availability with open-source projects. The whole point of open-source is anybody can clone the code and make future changes themselves in a fork if the project's author becomes temporarily or permanently unavailable. And, Pull Requests make it possible to eventually merge the fork back in if the author does become available again. Furthermore, this can be an opportunity to learn a new codebase and improve your software engineering skills. Do not waste it by whining about an author's lack of availability.

**Comment by myriad007** [comment]
Sorry Tim, my bad. Thanks for the info. 
For anyone else receiving the same error run: `pip install -U setuptools[core]`
