### ISSUE TITLE
KeyError: 'picture'

### ISSUE THREAD

**Issue by dev-geddy** [timrae/spotify_to_tidal#21]
I've followed all instructions, however getting this error when running the script. No ideas how to solve it...
```Traceback (most recent call last):
  File "sync.py", line 298, in <module>
    tidal_session = open_tidal_session()
  File "/Users/gediminas/WEB/learning/spotify_to_tidal/auth.py", line 48, in open_tidal_session
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidalapi/session.py", line 364, in _process_link_login
    self.user = tidalapi.User(self, user_id=json['userId']).factory()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidalapi/user.py", line 48, in factory
    return self.request.map_request('users/%s' % self.id, parse=self.parse)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidalapi/request.py", line 118, in map_request
    return self.map_json(json_obj, parse=parse)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidalapi/request.py", line 125, in map_json
    return parse(json_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidalapi/user.py", line 65, in parse
    return user.parse(json_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidalapi/user.py", line 104, in parse
    super(LoggedInUser, self).parse(json_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidalapi/user.py", line 77, in parse
    self.picture_id = json_obj['picture']
KeyError: 'picture'
```

**Comment by timrae** [comment]
See #19
