### ISSUE TITLE
No URL for authorization?

### ISSUE THREAD

**Issue by bibi-b** [timrae/spotify_to_tidal#23]
Hi there,

seems that I am doing something wrong. On a headless Ubuntu 20 I run: 

python3 sync.py

but nothing happens. I have to abort with ctrl-c to get back to the command line, where it then says:

Traceback (most recent call last):
  File "/home/meiko/spotify_to_tidal/sync.py", line 297, in <module>
    spotify_session = open_spotify_session(config['spotify'])
  File "/home/meiko/spotify_to_tidal/auth.py", line 16, in open_spotify_session
    credentials_manager.get_access_token(as_dict=False)
  File "/home/meiko/miniconda3/lib/python3.10/site-packages/spotipy/oauth2.py", line 535, in get_access_token
    "code": code or self.get_auth_response(),
  File "/home/meiko/miniconda3/lib/python3.10/site-packages/spotipy/oauth2.py", line 490, in get_auth_response
    return self._get_auth_response_local_server(redirect_port)
  File "/home/meiko/miniconda3/lib/python3.10/site-packages/spotipy/oauth2.py", line 459, in _get_auth_response_local_server
    server.handle_request()
  File "/home/meiko/miniconda3/lib/python3.10/socketserver.py", line 294, in handle_request
    ready = selector.select(timeout)
  File "/home/meiko/miniconda3/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

If I understand everything right, I should have get an URL for authorization, haven't I?

Thanks
meiko

**Comment by timrae** [comment]
How long did you wait before aborting?

**Comment by bibi-b** [comment]
@timrae About 30 min.

**Comment by timrae** [comment]
I see... Do you have X11 running? Usually it'll open up a browser window where you do the oauth authentication.

**Comment by bibi-b** [comment]
No, as it is an headless server I want to have it "lean". Any chance to get the URL in the command line?

**Comment by timrae** [comment]
I'd say the easiest way would be to use X11 forwarding to your local computer. I've never tried to run it on a headless server, so can't offer any support on this.

**Comment by bibi-b** [comment]
Okay, thank you. I'll try this.
