### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by zeus1921** [timrae/spotify_to_tidal#35]
spotify_to_tidal\sync.py", line 10, in <module>
    from .tidalapi_patch import set_tidal_playlist
ImportError: attempted relative import with no known parent package

How to solve this?

**Comment by timrae** [comment]
There have been a few changes recently, can you please try pull the latest version and follow the instructions in the updated readme file?

**Comment by ericou1** [comment]
I just downloaded 0.1.4 and I'm seeing a similar error when running `spotify_to_tidal`
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/cireou/spotify_to_tidal/src/spotify_to_tidal/__main__.py", line 5, in <module>
    from . import sync as _sync
ImportError: attempted relative import with no known parent package
```

**Comment by timrae** [comment]
Please provide exact reproduction steps including which environment you're
running it in

**Comment by samuelepecetto** [comment]
I ran into the same issue when debugging through vscode.
The solution is to add an empty `__init__.py` file alongside the main script.
Here's my debug config for reference:
```json
{
    "name": "Python Debugger: Current File",
    "type": "debugpy",
    "request": "launch",
    "module": "spotify_to_tidal",
    "console": "integratedTerminal"
}
```
