### ISSUE TITLE
ModuleNotFoundError: No module named 'spotify_to_tidal.type.config'

### ISSUE THREAD

**Issue by timrae** [timrae/spotify_to_tidal#38]
@joshrmcdaniel
Did you perhaps forget to commit some files? I can't run the project on `main`

```
python3 -m pip install -e .
spotify_to_tidal

Traceback (most recent call last):
  File "~/.pyenv/versions/3.10.12/bin/spotify_to_tidal", line 5, in <module>
    from spotify_to_tidal.__main__ import main
  File "src/spotify_to_tidal/__main__.py", line 5, in <module>
    from . import sync as _sync
  File "src/spotify_to_tidal/sync.py", line 16, in <module>
    from .type import spotify as t_spotify
  File "src/spotify_to_tidal/type/__init__.py", line 1, in <module>
    from .config import SpotifyConfig, TidalConfig, PlaylistConfig, SyncConfig
ModuleNotFoundError: No module named 'spotify_to_tidal.type.config'
```

**Comment by timrae** [comment]
Also the readme is out of date now I guess...

**Comment by joshrmcdaniel** [comment]
I'll fix this when I have time today. The type/config is the same as the one in my fork

**Comment by RobinHirst11** [comment]
i had issues too trying to run your repo, 

will give reason when im home, i dont remember off the top of my head
