### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by timrae** [timrae/spotify_to_tidal#50]
Would be great if someone were to setup some basic integration tests with Circle CI or something

**Comment by xerexcoded** [comment]
Hey could you assign this issue to me, i would like  to give it a try

**Comment by xerexcoded** [comment]
**I am getting this error when trying to run after building the script.**

❯ spotify_to_tidal

> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\arnav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\spotify_to_tidal.exe\__main__.py", line 4, in <module>
>   File "C:\Users\arnav\OSS contri\spotify_to_tidal\src\spotify_to_tidal\__main__.py", line 5, in <module>
>     from . import sync as _sync
>   File "C:\Users\arnav\OSS contri\spotify_to_tidal\src\spotify_to_tidal\sync.py", line 157, in <module>
>     async def get_tracks_from_spotify_playlist(spotify_session: spotipy.Spotify, spotify_playlist: t_spotify.SpotifyPlaylist):

                                                                                                   

```bash
^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'spotify_to_tidal.type.spotify' has no attribute 'SpotifyPlaylist'. Did you mean: 'SpotifyArtist'?
```


**am i using the CLI wrong or is it something else?**

**Comment by timrae** [comment]
Thanks, gimme a couple of minutes, looks like I accidentally introduced a bug the other day, this is exactly why we need CI!

**Comment by timrae** [comment]
Done

**Comment by xerexcoded** [comment]
I will check it out, thank you.

**Comment by xerexcoded** [comment]
Hello,

I apologize for the delayed response; I was unwell.

I would like to outline my thought process for your feedback.

I plan to take the following steps:
- Write basic unit tests for all the files.
- Write integration tests to verify the synchronization flow.
- Use `pytest` as the testing module and `pytest-mock` for mocking dependencies.

After this, I will integrate the tests to work with CircleCI.

Looking forward to your input.

Best regards

**Comment by timrae** [comment]
Sounds great. How would the integration tests work though? I guess we'd need to have test accounts for Spotify and Tidal in order to authorise

**Comment by xerexcoded** [comment]
yes that is correct we would require accounts from both spotify and tidal to test the synchronisation flow.

In my country tidal is not available.
Could you create dummy accounts maybe which we can use for the tests.

for unit test however we are good by using mock data.

**Comment by timrae** [comment]
There are a few problems with this:

1. Currently the authorization flow requires user intervention to authorize the app via the browser, so it's not suitable for a CI
2. While Spotify has a free version which we could perhaps use for integration testing, Tidal currently does not. It may or may not be possible to modify playlists without an active subscription, this is something we could try I guess, but we still have problem 1.

**Comment by c0ball** [comment]
Wouldn't this also be a good time to establish a style guide? So to add a stage with a style guide enforce like flake8 or ruff?

**Comment by xerexcoded** [comment]
I will start with the unit test and CI integration for now and maybe try the following:-

1. **Automate Authorization Flow**:
   - Use OAuth 2.0 Authorization Code Flow with PKCE for Spotify.
   - Pre-authorize the app and use a refresh token to automate token renewal in CI environments.

2. **Mock API for Tidal**:
   - Create a mock server to simulate Tidal's API responses.
   - Use tools like `responses` to mock API endpoints for integration testing.

**Comment by xerexcoded** [comment]
I added basic circle CI config with this PR https://github.com/spotify2tidal/spotify_to_tidal/pull/59

**Comment by xerexcoded** [comment]
> Wouldn't this also be a good time to establish a style guide? So to add a stage with a style guide enforce like flake8 or ruff?

maybe i could perhaps take this up in another PR ?

**Comment by xerexcoded** [comment]
@timrae can you check the PR, I have cleaned up the commit history.

**Comment by xerexcoded** [comment]
Hey @timrae , I pulled from `upstream`, one test method was failing `test_auth.py`, because my test methods did not cover the 
`user-library-read` scope. 
As this scope was added in https://github.com/spotify2tidal/spotify_to_tidal/commit/54526a0306d463c7c4b0c060b7b5504a17d8b682 , it was added after I forked.

I will fix it and create another PR, also would you like me to add ruff or flake8 for linting?

**Comment by timrae** [comment]
Just make small targeted PR's is best for me

**Comment by xerexcoded** [comment]
I have fixed the test here https://github.com/spotify2tidal/spotify_to_tidal/pull/68, let me know when the tests pass in circle-ci

**Comment by xerexcoded** [comment]
Hey @timrae, hopefully the tests are working now in the circle-ci dashboard

**Comment by timrae** [comment]
@xerexcoded yes thank you, there is a green tick on the commit in GitHub also. It would be great to have some more unit tests if you still feel like working on this. Especially the main sync playlist function, and coming up with various test cases for the matching algorithms

**Comment by xerexcoded** [comment]
@timrae sure. I will write more tests to cover all the unit test cases and hopefully also cover up integration tests.
