### ISSUE TITLE
missing 'Adding new tracks to Tidal favorites' part

### ISSUE THREAD

**Issue by ogoor93** [timrae/spotify_to_tidal#78]
HI,
After searching for Tidal tracks in Spotify, priting missing tracks, I see only below errors. Any tips how to solve this issue? 

Traceback (most recent call last):
  File "C:\Users\ogoor\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ogoor\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ogoor\AppData\Local\Programs\Python\Python310\Scripts\spotify_to_tidal.exe\__main__.py", line 7, in <module>
  File "C:\Users\ogoor\spotify_to_tidal\src\spotify_to_tidal\__main__.py", line 42, in main
    _sync.sync_favorites_wrapper(spotify_session, tidal_session, config)
  File "C:\Users\ogoor\spotify_to_tidal\src\spotify_to_tidal\sync.py", line 345, in sync_favorites_wrapper
    asyncio.run(main=sync_favorites(spotify_session=spotify_session, tidal_session=tidal_session, config=config))
  File "C:\Users\ogoor\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ogoor\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\ogoor\spotify_to_tidal\src\spotify_to_tidal\sync.py", line 331, in sync_favorites
    await search_new_tracks_on_tidal(tidal_session, spotify_tracks, "Favorites", config)
  File "C:\Users\ogoor\spotify_to_tidal\src\spotify_to_tidal\sync.py", line 280, in search_new_tracks_on_tidal
    file.write(f"{song}\n")
  File "C:\Users\ogoor\AppData\Local\Programs\Python\Python310\lib\encodings\cp1250.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 24-31: character maps to <undefined>

**Comment by timrae** [comment]
Hi thanks for reporting, I've pushed a fix for this, let me know if you're still having issues after updating

**Comment by ogoor93** [comment]
irhgt now it works, thank you
