### ISSUE TITLE
Error, running module without arguments

### ISSUE THREAD

**Issue by DataPhaseDan** [timrae/spotify_to_tidal#94]
## Expected Behavior
to have a default configuration when none is specified.

## Actual Behavior
when running the module without flags, it errors.

## Steps to Reproduce the Problem

  1. python -m spotify_to_tidal
  ```bash 
PS F:\spotify_to_tidal> python -m spotify_to_tidal
Opening Spotify session
Opening Tidal session
Loading Spotify playlists
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "F:\spotify_to_tidal\src\spotify_to_tidal\__main__.py", line 45, in <module>
    main()
    ~~~~^^
  File "F:\spotify_to_tidal\src\spotify_to_tidal\__main__.py", line 38, in main
    _sync.sync_playlists_wrapper(spotify_session, tidal_session, _sync.get_user_playlist_mappings(spotify_session, tidal_session, config), config)
                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\spotify_to_tidal\src\spotify_to_tidal\sync.py", line 367, in get_user_playlist_mappings
    spotify_playlists = asyncio.run(get_playlists_from_spotify(spotify_session, config))
  File "C:\Users\danie\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "F:\spotify_to_tidal\src\spotify_to_tidal\sync.py", line 392, in get_playlists_from_spotify
    return list(filter( exclude_filter, filter( my_playlist_filter, playlists )))
  File "F:\spotify_to_tidal\src\spotify_to_tidal\sync.py", line 390, in <lambda>
    my_playlist_filter = lambda p: p['owner']['id'] == user_id
                                   ~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

  2.  python -m spotify_to_tidal --sync-favorites
 
 ```bash
PS F:\spotify_to_tidal> python -m spotify_to_tidal --sync-favorites
Opening Spotify session
Opening Tidal session
Loading favorite tracks from Spotify
Fetching additional data chunks: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 10.46it/s]
Loading existing favorite tracks from Tidal
Fetching additional data chunks: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 11.86it/s]
Searching Tidal for 1/74 tracks in Spotify playlist 'Favorites': 100%|████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.01it/s]
Adding new tracks to Tidal favorites: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.19it/s]
```

## Specifications

  - Version:  "1.0.3"
  - Platform: 
   OS Name: Microsoft Windows 11 Pro
   OS Version: 10.0.22631 N/A Build 22631

  - Subsystem: -

**Comment by DataPhaseDan** [comment]
after researching, it seems this error comes from non-user playlists in this example spotify owned playlists, which explains line 
```python 
  File "F:\spotify_to_tidal\src\spotify_to_tidal\sync.py", line 390, in <lambda>
    my_playlist_filter = lambda p: p['owner']['id'] == user_id
```

regards Daniel

**Comment by timrae** [comment]
Do you have a link to a playlist which causes this issue?

**Comment by timrae** [comment]
Does this fix it?

https://github.com/spotify2tidal/spotify_to_tidal/commit/2f1985a42b6b356cdf2358bc126a60b1492ac357

**Comment by timrae** [comment]
Great thanks for letting me know

**Comment by DataPhaseDan** [comment]
yes, 

```powershell
PS F:\spotify_to_tidal> python -m spotify_to_tidal
Opening Spotify session
Opening Tidal session
Loading Spotify playlists
Loading playlists from Tidal user
Loading tracks from Spotify playlist 'My Playlist #10'
Loading tracks from Spotify playlist 'My Playlist #9'
Loading tracks from Spotify playlist 'My Playlist #8'
Loading tracks from Spotify playlist 'My Playlist #7'
Loading tracks from Spotify playlist 'My Playlist #6'
Loading tracks from Spotify playlist 'shared playlist didi'
Loading tracks from Tidal playlist 'shared playlist didi'
No changes to write to Tidal playlist
Loading tracks from Spotify playlist 'Alien'
Loading tracks from Tidal playlist 'Alien'
No changes to write to Tidal playlist
Loading tracks from Spotify playlist 'My Playlist #3'
Loading tracks from Spotify playlist 'StyleBox'
Loading tracks from Tidal playlist 'StyleBox'
No changes to write to Tidal playlist
Loading tracks from Spotify playlist 'Radio-Favoriten'
No playlist found on Tidal corresponding to Spotify playlist: 'Radio-Favoriten', creating new playlist
Searching Tidal for 1/1 tracks in Spotify playlist 'Radio-Favoriten': 100%|████████████████████████████| 1/1 [00:00<00:00,  2.70it/s]
Adding new tracks to Tidal playlist: 100%|█████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.06s/it]
Loading favorite tracks from Spotify
Fetching additional data chunks: 100%|█████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 10.59it/s]
Loading existing favorite tracks from Tidal
Fetching additional data chunks: 100%|█████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 11.98it/s]
No new tracks to add to Tidal favorites
PS F:\spotify_to_tidal>

```

Thanks
