### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by ArjonBu** [timrae/spotify_to_tidal#97]
```
✖  spotify_to_tidal
Opening Spotify session
Opening Tidal session
Loading Spotify playlists
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.56it/s]
Traceback (most recent call last):
  File "/opt/homebrew/bin/spotify_to_tidal", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/arjon/spotify/spotify_to_tidal/src/spotify_to_tidal/__main__.py", line 38, in main
    _sync.sync_playlists_wrapper(spotify_session, tidal_session, _sync.get_user_playlist_mappings(spotify_session, tidal_session, config), config)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arjon/spotify/spotify_to_tidal/src/spotify_to_tidal/sync.py", line 367, in get_user_playlist_mappings
    spotify_playlists = asyncio.run(get_playlists_from_spotify(spotify_session, config))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/arjon/spotify/spotify_to_tidal/src/spotify_to_tidal/sync.py", line 392, in get_playlists_from_spotify
    return list(filter( exclude_filter, filter( my_playlist_filter, playlists )))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arjon/spotify/spotify_to_tidal/src/spotify_to_tidal/sync.py", line 390, in <lambda>
    my_playlist_filter = lambda p: p['owner']['id'] == user_id
                                   ~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

config.yml
```
spotify:
  client_id: XXXX
  client_secret: XXXX
  username: XXXX
  redirect_uri: http://localhost:8888/callback
  open_browser: True # Set to False if using a headless server environment

sync_favorites_default: False
max_concurrency: 10 # max concurrent connections at any given time
rate_limit:      10 # max sustained connections per second
```

I did install all python dependencies. I am using a M1 Mac mini. 

Any ideas?

**Comment by timrae** [comment]
Does this fix it?

https://github.com/spotify2tidal/spotify_to_tidal/commit/2f1985a42b6b356cdf2358bc126a60b1492ac357

**Comment by ArjonBu** [comment]
Seems like it does! Thank you!

**Comment by timrae** [comment]
Great thanks for letting me know
